import MetricCard from "../components/metric-card";
import { demoDetections, demoQuality } from "../state/demo-data";

export default function AnalyticsPage() {
  const classes = ["Ghost Net", "Metal", "Rock", "Cable", "Coral", "Sand Ripple"];
  const priorities = ["high", "medium", "low", "uncertain"] as const;
  const classCounts = classes.map((type) => ({ type, count: demoDetections.filter((item) => item.type === type).length }));
  return <div className="page-section"><div className="page-intro"><div><span className="eyebrow">SURVEY INSIGHTS · DEMO DATA</span><h2>Analytics</h2><p>Classification and priority patterns from the shared sample detection set.</p></div><span className="live-indicator">37 SAMPLE DETECTIONS</span></div>
    <div className="analytics-metrics"><MetricCard label="Scans analyzed" value="128" /><MetricCard label="Object detections" value="37" tone="warning" /><MetricCard label="Scan quality" value={`${demoQuality.overall}%`} tone="verified" /><MetricCard label="High priority" value="08" tone="warning" /></div>
    <div className="analytics-grid"><section className="panel chart-panel"><div className="section-heading"><div><span className="eyebrow">OBJECT CLASSES</span><h3>Classification breakdown</h3></div></div>{classCounts.map(({ type, count }) => <div className="bar-row" key={type}><span>{type}</span><div><i style={{ width: `${(count / demoDetections.length) * 100}%` }} /></div><strong>{count}</strong></div>)}</section><section className="panel chart-panel"><div className="section-heading"><div><span className="eyebrow">RESPONSE LEVELS</span><h3>Priority breakdown</h3></div></div>{priorities.map((priority) => { const count = demoDetections.filter((item) => item.priority === priority).length; return <div className="priority-stat" key={priority}><span className={`priority-pill priority-${priority}`}><i />{priority}</span><strong>{String(count).padStart(2, "0")}</strong><small>{Math.round((count / demoDetections.length) * 100)}%</small></div>; })}</section></div>
    <section className="panel quality-panel"><div className="section-heading"><div><span className="eyebrow">SCAN QUALITY</span><h3>Overall quality: {demoQuality.overall}%</h3></div><span className="quality-ring">{demoQuality.overall}%</span></div><div className="quality-table"><div><strong>Parameter</strong><strong>Status</strong></div><div><span>Speckle Noise</span><span className="state-good">✓ Good</span></div><div><span>Data Gaps</span><span className="state-good">✓ Low</span></div><div><span>Motion Distortion</span><span className="state-warning">⚠ Moderate</span></div><div><span>Coverage</span><span className="state-good">✓ Good</span></div></div><div className="quality-alert"><strong>⚠ Rescan Recommended</strong><p>Motion distortion may affect detection reliability. Verify this area with a secondary pass.</p></div></section>
  </div>;
}
