import { demoDetections } from "../state/demo-data";

type Props = { selectedDetectionId: number | null; onSelectDetection: (id: number) => void; onViewSonar: () => void };
const points = [[18, 22], [35, 35], [55, 19], [71, 41], [82, 28], [28, 66], [48, 74], [67, 63], [85, 75], [11, 48], [41, 49], [61, 32]] as const;
export default function DetectionMapPage({ selectedDetectionId, onSelectDetection, onViewSonar }: Props) {
  const selected = demoDetections.find((item) => item.id === selectedDetectionId);
  return <div className="page-section"><div className="page-intro"><div><span className="eyebrow">SURVEY COVERAGE · DEMO</span><h2>Marine detection map</h2><p>Illustrative survey grid with sample detection locations and sonar coverage tracks.</p></div><span className="live-indicator">NOT LIVE GPS</span></div>
    <div className="map-layout"><section className="marine-map" aria-label="Illustrative marine survey map"><div className="map-coordinate map-nw">18° 42′ N</div><div className="map-coordinate map-se">72° 51′ E</div><svg viewBox="0 0 1000 700" preserveAspectRatio="none" aria-hidden="true"><path d="M110 590 Q160 120 260 110 Q380 100 420 600 M270 610 Q330 70 480 80 Q620 85 650 610 M450 620 Q500 80 690 115 Q820 135 860 620 M615 610 Q690 90 920 180"/><path d="M40 510 Q380 425 960 360 M40 310 Q440 280 940 220" className="coverage-track-secondary"/></svg>
      {points.map(([left, top], index) => { const detection = demoDetections[index]; if (!detection) return null; return <button key={detection.id} className={`map-marker priority-${detection.priority}${selectedDetectionId === detection.id ? " is-selected" : ""}`} style={{ left: `${left}%`, top: `${top}%` }} aria-label={`Detection ${detection.id}, ${detection.type}, ${detection.priority} priority`} onClick={() => onSelectDetection(detection.id)}><span>{detection.id}</span></button>; })}
      <div className="map-legend">{(["high", "medium", "low", "uncertain"] as const).map((priority) => <span key={priority}><i className={`priority-${priority}`} />{priority}</span>)}</div>
    </section><aside className="panel map-detail"><span className="eyebrow">SELECTED MARKER</span>{selected ? <><h3>Detection #{selected.id}</h3><strong>{selected.type}</strong><p>Confidence: {selected.confidence === null ? "—" : `${selected.confidence}%`}<br />Size: {selected.estimatedSizeM === null ? "—" : `~${selected.estimatedSizeM} m`}<br />Status: {selected.status.replaceAll("-", " ")}</p><p className="mono">{selected.latitude}<br />{selected.longitude}</p><button className="primary-button" onClick={onViewSonar}>View sonar ↓</button></> : <p className="muted">Choose a map marker to see its details.</p>}<small className="demo-note">All locations shown are illustrative demo coordinates.</small></aside></div></div>;
}
